build-ido:
	cargo contract build --manifest-path ido/Cargo.toml

build-ido-factory:
	cargo contract build --manifest-path ido_factory/Cargo.toml

build-staking:
	cargo contract build --manifest-path staking/Cargo.toml

build-token:
	cargo contract build --manifest-path token/Cargo.toml

build-token-factory:
	cargo contract build --manifest-path token_factory/Cargo.toml